import type { Metadata } from 'next';
import { Anybody, Inter } from 'next/font/google';
import './globals.css';
import Nav from './Nav';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
});

const anybody = Anybody({
    subsets: ['latin'],
    variable: '--font-anybody',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${anybody.variable} ${inter.variable} antialiased bg-secondary`}>
                <div className='max-w-[1200px] mx-auto h-screen'>
                    <Nav />
                    {children}
                </div>
            </body>
        </html>
    );
}
